### ISSUE TITLE
imsave is depreciated in scipy

### ISSUE THREAD

**Issue by foundway** [maajor/NeuralNetworkPostProcessing#5]
Hi,
I am trying to follow the steps using fast-style-transfer to train. But when I run
`python3 train_fst.py --style chinese_landscape.jp`
I got this error:
`Traceback (most recent call last):
  File "train_fst.py", line 6, in <module>
    from scipy.misc import imsave
ImportError: cannot import name 'imsave' from 'scipy.misc' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scipy/misc/__init__.py)
`
I am using the latest TensorFlow 2.3.0 and recommended scipy 1.4.1. Sounds like imsave is depreciated in newer version of scipy. Do you know how I can workaround this issue?

**Comment by maajor** [comment]
Hi, I have upgraded the training code to support TF2.0, 
see https://github.com/maajor/NeuralNetworkPostProcessing/commit/2264c8d57b995d48fdd708cb28dba61c5cff7785

Best Regards,
MYD
